"""Tests for the hand-rolled PDF layout parser (D2).

Runs against the three real fixture PDFs in packages/kb/golden/pdf/.
All tests are pure-CPU (no live API calls) and use the -m "not live" gate.

Fixture PDFs were generated by golden/pdf/generate_fixtures.py:
  - 01-安康保障计划条款.pdf  (3 pages: H1=18pt, H2=15pt, body=10.5pt, table on p2)
  - 02-理赔指南.pdf          (2 pages)
  - 03-产品说明.pdf          (2 pages)
Every page has a 9pt header "星辉人寿保险股份有限公司" and footer "第 N 页".
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from anvil_kb.ingest.chunker import chunk_markdown
from anvil_kb.ingest.pdf import parse_pdf

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PDF_DIR = Path(__file__).parent.parent / "golden" / "pdf"
CORPUS_DIR = Path(__file__).parent.parent / "golden" / "corpus"

CLAUSE_PDF = PDF_DIR / "01-安康保障计划条款.pdf"
GUIDE_PDF = PDF_DIR / "02-理赔指南.pdf"
PRODUCT_PDF = PDF_DIR / "03-产品说明.pdf"

ALL_PDFS = [CLAUSE_PDF, GUIDE_PDF, PRODUCT_PDF]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _norm(text: str) -> str:
    """Collapse all whitespace (including NBSP, ideographic space) into nothing.

    Used for "is this string present?" checks that shouldn't fail on
    typographic spacing differences between the PDF and the golden corpus.
    """
    return re.sub(r"\s+", "", text)


def _load_pdf(path: Path) -> str:
    """Read a fixture PDF and return the parsed markdown."""
    return parse_pdf(path.read_bytes())


# ---------------------------------------------------------------------------
# Test 7 (bad input) — run first so failures are obvious
# ---------------------------------------------------------------------------

def test_bad_input_raises_value_error() -> None:
    """Random bytes that are not a valid PDF must raise ValueError."""
    with pytest.raises(ValueError, match="not a valid PDF"):
        parse_pdf(b"\x00\x01\x02\x03NOT_A_PDF_AT_ALL" * 50)


def test_empty_bytes_raises_value_error() -> None:
    """Empty bytes must also raise ValueError."""
    with pytest.raises(ValueError, match="not a valid PDF"):
        parse_pdf(b"")


# ---------------------------------------------------------------------------
# Test 1 — header/footer removal
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("pdf_path", ALL_PDFS, ids=["条款", "理赔指南", "产品说明"])
def test_company_header_removed(pdf_path: Path) -> None:
    """Repeated page-header occurrences of the company name must be stripped.

    The header "星辉人寿保险股份有限公司" appears on every page (9pt, top zone).
    After parsing, the company name should appear at most ONCE in the output
    (because 03-产品说明.md legitimately mentions it in the body text once).
    Documents 01 and 02 have no body-text mention, so count must be 0 for
    those; document 03 may have 1 due to legitimate body content.

    Crucially, the number of occurrences must be LESS than the number of pages
    (i.e. the cross-page dedup worked — the header was not emitted once per page).
    """
    md = _load_pdf(pdf_path)
    normalised = _norm(md)
    company = _norm("星辉人寿保险股份有限公司")
    count = normalised.count(company)

    import pdfplumber
    with pdfplumber.open(pdf_path) as pdf:
        num_pages = len(pdf.pages)

    assert count < num_pages, (
        f"{pdf_path.name}: company header appears {count} times "
        f"(must be < {num_pages} pages — dedup must have reduced repetitions).\n"
        f"First 300 chars of output:\n{md[:300]}"
    )


@pytest.mark.parametrize("pdf_path", ALL_PDFS, ids=["条款", "理赔指南", "产品说明"])
def test_page_numbers_removed(pdf_path: Path) -> None:
    """Page-number footers like 「第1页」/ 「第 2 页」 must NOT appear in output."""
    md = _load_pdf(pdf_path)
    normalised = _norm(md)
    # Match patterns: 第N页, 第 N 页, N/M, - N -, etc.
    for page_num in range(1, 10):
        assert f"第{page_num}页" not in normalised, (
            f"{pdf_path.name}: page-number '第{page_num}页' leaked into output."
        )


# ---------------------------------------------------------------------------
# Test 2 — heading recognition (≥80% of corpus ## headings identified)
# ---------------------------------------------------------------------------

def _corpus_h2_headings(md_text: str) -> list[str]:
    """Extract the titles of all ## headings from a corpus markdown file."""
    return re.findall(r"^## (.+)", md_text, re.MULTILINE)


def _output_heading_lines(md_text: str) -> set[str]:
    """Return the text content of all heading lines (any level) in output md."""
    titles: set[str] = set()
    for line in md_text.splitlines():
        m = re.match(r"^#{1,3} (.+)", line)
        if m:
            titles.add(_norm(m.group(1)))
    return titles


@pytest.mark.parametrize(
    "pdf_path,corpus_path",
    [
        (CLAUSE_PDF, CORPUS_DIR / "01-安康保障计划条款.md"),
        (GUIDE_PDF, CORPUS_DIR / "02-理赔指南.md"),
        (PRODUCT_PDF, CORPUS_DIR / "03-产品说明.md"),
    ],
    ids=["条款", "理赔指南", "产品说明"],
)
def test_heading_recognition_80pct(pdf_path: Path, corpus_path: Path) -> None:
    """≥80% of the golden corpus ## headings must appear as heading lines in output."""
    corpus_md = corpus_path.read_text(encoding="utf-8")
    golden_headings = _corpus_h2_headings(corpus_md)
    assert golden_headings, f"No ## headings found in {corpus_path.name}"

    parsed_md = _load_pdf(pdf_path)
    output_heading_titles = _output_heading_lines(parsed_md)

    matched = [h for h in golden_headings if _norm(h) in output_heading_titles]
    ratio = len(matched) / len(golden_headings)

    assert ratio >= 0.80, (
        f"{pdf_path.name}: only {len(matched)}/{len(golden_headings)} "
        f"({ratio:.0%}) headings recognised (need ≥80%).\n"
        f"Missing: {[h for h in golden_headings if _norm(h) not in output_heading_titles]}\n"
        f"Output heading lines found: {sorted(output_heading_titles)}"
    )


# ---------------------------------------------------------------------------
# Test 3 — table extraction
# ---------------------------------------------------------------------------

def test_table_present_in_clause_output() -> None:
    """条款篇 output must contain markdown table rows (| prefix)."""
    md = _load_pdf(CLAUSE_PDF)
    table_lines = [ln for ln in md.splitlines() if ln.startswith("|")]
    assert len(table_lines) >= 4, (
        f"Expected ≥4 table lines in 条款篇 output, got {len(table_lines)}.\n"
        f"Table lines found: {table_lines}"
    )


def test_table_separator_row_present() -> None:
    """Markdown table must have a |---| separator row."""
    md = _load_pdf(CLAUSE_PDF)
    has_separator = any(re.match(r"^\|[-:| ]+\|", ln) for ln in md.splitlines())
    assert has_separator, "No |---| separator row found in 条款篇 output."


def test_insurance_amount_in_table() -> None:
    """「保险金额的30%」must appear inside a table row (| prefix)."""
    md = _load_pdf(CLAUSE_PDF)
    table_lines = [ln for ln in md.splitlines() if ln.startswith("|")]
    table_text = "\n".join(table_lines)
    assert _norm("保险金额的30%") in _norm(table_text), (
        "「保险金额的30%」not found in table rows.\n"
        f"Table rows:\n{table_text}"
    )


# ---------------------------------------------------------------------------
# Test 4 — factual fidelity (key clauses present in respective docs)
# ---------------------------------------------------------------------------

def test_waiting_period_in_clause() -> None:
    """「等待期为90天」must appear in 条款篇 output (normalised)."""
    md = _load_pdf(CLAUSE_PDF)
    assert "等待期为90天" in _norm(md), (
        "Key clause '等待期为90天' not found in 条款篇 output.\n"
        f"Snippet: {md[:1000]}"
    )


def test_hesitation_period_in_clause() -> None:
    """「犹豫期」must appear in 条款篇 output."""
    md = _load_pdf(CLAUSE_PDF)
    assert "犹豫期" in md, "'犹豫期' not found in 条款篇 output."


def test_premium_example_in_product() -> None:
    """「6800」(annual premium example) must appear in 产品说明 output."""
    md = _load_pdf(PRODUCT_PDF)
    assert "6800" in _norm(md), (
        "'6800' not found in 产品说明 output.\n"
        f"Snippet: {md[:1000]}"
    )


def test_waiting_period_in_product() -> None:
    """「等待期90天」must appear in 产品说明 output (normalised)."""
    md = _load_pdf(PRODUCT_PDF)
    assert "等待期90天" in _norm(md), (
        "'等待期90天' not found in 产品说明 output."
    )


# ---------------------------------------------------------------------------
# Test 5 — no double-printing of table content
# ---------------------------------------------------------------------------

def test_no_double_table_content() -> None:
    """「保险金额的30%」must not appear more times than in the source corpus.

    The corpus (01-安康保障计划条款.md) contains:
      - 1 occurrence in body text (第8条 sentence)
      - 3 occurrences in table rows (第1次/第2次/第3次)
    Total: 4 occurrences.  If bbox dedup fails, the same table rows would also
    be emitted as raw text lines, doubling the count to 7.  We assert ≤ 4.
    """
    md = _load_pdf(CLAUSE_PDF)
    normalised = _norm(md)
    target = _norm("保险金额的30%")
    count = normalised.count(target)

    # Ground-truth count from corpus
    corpus_md = (CORPUS_DIR / "01-安康保障计划条款.md").read_text(encoding="utf-8")
    expected_count = _norm(corpus_md).count(target)

    assert count <= expected_count, (
        f"'保险金额的30%' appears {count} times in output (corpus has {expected_count}; "
        "excess indicates bbox-based table dedup failed)."
    )


# ---------------------------------------------------------------------------
# Test 6 — downstream chunker compatibility
# ---------------------------------------------------------------------------

def test_chunk_markdown_compat_clause() -> None:
    """chunk_markdown(parse_pdf(条款pdf)) must not raise and produce ≥5 chunks."""
    md = _load_pdf(CLAUSE_PDF)
    chunks = chunk_markdown(md)
    assert len(chunks) >= 5, (
        f"Expected ≥5 chunks for 条款篇, got {len(chunks)}."
    )


def test_table_chunk_atomic_in_clause() -> None:
    """chunk_markdown output must contain at least one chunk starting with '|'.

    Tables must be emitted as atomic chunks by the chunker.
    """
    md = _load_pdf(CLAUSE_PDF)
    chunks = chunk_markdown(md)
    table_chunks = [c for c in chunks if c.content.startswith("|")]
    assert len(table_chunks) >= 1, (
        "No atomic table chunk (starting with '|') found in chunk_markdown output.\n"
        f"All chunk starts: {[c.content[:30] for c in chunks]}"
    )
